const fetchData = () => {
  return {
    edges: [
      { source: "SubscribeAndSaveOfferData", target: "SubscribeAndSaveOneTimePurchaseSavings" },
      { source: "CustomizationToken", target: "DetailPageCustomId" },
      { source: "CustomizationToken", target: "Customization" },
      { source: "CustomizationToken", target: "CustomizedThumbnail" },
      { source: "CompanyCompliancePolicy", target: "RestrictedByYourCompanyCart" },
      { source: "PantryOrderThreshold", target: "UnpurchasableByPantry" },
      { source: "Addon", target: "UnpurchasableByPantry" },
      { source: "Pantry", target: "UnpurchasableByPantry" },
      { source: "PantryOrderThreshold", target: "PantryMinimumOrderViolation" },
      { source: "AddedTime", target: "MostRecentlyAddedItem" },
      { source: "PrimeMembership", target: "LineItemBuyNow" },
      { source: "BuyNow", target: "LineItemBuyNow" },
      { source: "BusinessCustomerMembership", target: "BusinessPriceBadge" },
      { source: "Quantity", target: "BusinessPriceBadge" },
      { source: "BusinessPriceType", target: "BusinessPriceBadge" },
      { source: "ItemKeyValuePairs", target: "IncentivizedCartUrl" },
      { source: "FulfillmentManagerId", target: "IncentivizedCartUrl" },
      { source: "PrimeMembership", target: "IncentivizedCartUrl" },
      { source: "Price", target: "IncentivizedCartUrl" },
      { source: "Quantity", target: "IncentivizedCartUrl" },
      { source: "ProductGroupUntyped", target: "IncentivizedCartUrl" },
      { source: "OfferingSku", target: "IncentivizedCartUrl" },
      { source: "Fulfillment", target: "IncentivizedCartUrl" },
      { source: "CustomerBenefitSavingsBase", target: "CustomerBenefitPriceSavings" },
      { source: "SavedCartErroneousImportantMessageList", target: "PriceChange" },
      { source: "Price", target: "PriceChange" },
      { source: "ActiveCartErroneousImportantMessageList", target: "PriceChange" },
      { source: "PreviousPrice", target: "PriceChange" },
      { source: "GiftCardCustomizationId", target: "GiftCardCustomization" },
      { source: "CartBrandBase", target: "UltraFastGrocery" },
      { source: "ItemBrandBase", target: "UltraFastGrocery" },
      { source: "AmbiguousBrandBase", target: "UltraFastGrocery" },
      { source: "CartBrandBase", target: "Destination" },
      { source: "ItemBrandBase", target: "Destination" },
      { source: "AmbiguousBrandBase", target: "Destination" },
      { source: "CartBrandBase", target: "AddressIsPickup" },
      { source: "ItemBrandBase", target: "AddressIsPickup" },
      { source: "AmbiguousBrandBase", target: "AddressIsPickup" },
      { source: "CartBrandBase", target: "BrandId" },
      { source: "ItemBrandBase", target: "BrandId" },
      { source: "AmbiguousBrandBase", target: "BrandId" },
      { source: "CartBrandBase", target: "PostOrderOverAuthMessage" },
      { source: "ItemBrandBase", target: "PostOrderOverAuthMessage" },
      { source: "AmbiguousBrandBase", target: "PostOrderOverAuthMessage" },
      { source: "CartBrandBase", target: "RegionHasPickup" },
      { source: "ItemBrandBase", target: "RegionHasPickup" },
      { source: "AmbiguousBrandBase", target: "RegionHasPickup" },
      { source: "CartBrandBase", target: "RegionId" },
      { source: "ItemBrandBase", target: "RegionId" },
      { source: "AmbiguousBrandBase", target: "RegionId" },
      { source: "CartBrandBase", target: "SelectedOpenOrder" },
      { source: "ItemBrandBase", target: "SelectedOpenOrder" },
      { source: "AmbiguousBrandBase", target: "SelectedOpenOrder" },
      { source: "AddedTime", target: "AddedWithInSixMonths" },
      { source: "AddedTime", target: "AddedWithInAWeek" },
      { source: "Currency", target: "PartialServerSetting" },
      { source: "ClientSideViewModel", target: "PartialServerSetting" },
      { source: "Price", target: "SnapEbtItemSubtotals" },
      { source: "Currency", target: "SnapEbtItemSubtotals" },
      { source: "SnapEbtEligibility", target: "SnapEbtItemSubtotals" },
      { source: "UnitOfMeasureEstimatedItemSubtotal", target: "SnapEbtItemSubtotals" },
      { source: "ProductBundleDetail", target: "SnapEbtItemSubtotals" },
      { source: "Quantity", target: "SnapEbtItemSubtotals" },
      { source: "Pantry", target: "PantryPurchaseEligible" },
      { source: "Pantry", target: "PantryBox" },
      { source: "PantryBoxBuilding", target: "PantryBox" },
      { source: "RemoteFbaMessage", target: "Seller" },
      { source: "ProductType", target: "Seller" },
      { source: "AmazonGlobalStoreSeller", target: "Seller" },
      { source: "ProductGroup", target: "Seller" },
      { source: "GiftCardCustomization", target: "Seller" },
      { source: "SellerBase", target: "Seller" },
      { source: "GiftCardCustomization", target: "GroupGiftingProductImage" },
      { source: "RegistryItemAsin", target: "GroupGiftingProductImage" },
      { source: "GiftCardCustomization", target: "GroupGiftingProductTitle" },
      { source: "RegistryItemAsin", target: "GroupGiftingProductTitle" },
      { source: "Price", target: "InstallmentsDetail" },
      { source: "Installments", target: "InstallmentsDetail" },
      { source: "PrimeMembership", target: "MovableToCart" },
      { source: "PrimeExclusiveConfig", target: "MovableToCart" },
      { source: "ProductType", target: "MovableToCart" },
      { source: "PrimeProgramEligibility", target: "MovableToCart" },
      { source: "MembershipRetailPipelineConfig", target: "MovableToCart" },
      { source: "MembershipSharedConfig", target: "MovableToCart" },
      { source: "BuyboxWinner", target: "MovableToCart" },
      { source: "UnavailableOffer", target: "MovableToCart" },
      { source: "PantryPurchaseEligible", target: "MovableToCart" },
      { source: "ProductGroup", target: "MovableToCart" },
      { source: "Pantry", target: "MovableToCart" },
      { source: "Availability", target: "MovableToCart" },
      { source: "PrimeMembership", target: "MovableToWishlist" },
      { source: "PrimeExclusiveConfig", target: "MovableToWishlist" },
      { source: "ProductType", target: "MovableToWishlist" },
      { source: "PrimeProgramEligibility", target: "MovableToWishlist" },
      { source: "MembershipRetailPipelineConfig", target: "MovableToWishlist" },
      { source: "MembershipSharedConfig", target: "MovableToWishlist" },
      { source: "BuyboxWinner", target: "MovableToWishlist" },
      { source: "UnavailableOffer", target: "MovableToWishlist" },
      { source: "PantryPurchaseEligible", target: "MovableToWishlist" },
      { source: "ProductGroup", target: "MovableToWishlist" },
      { source: "Pantry", target: "MovableToWishlist" },
      { source: "Availability", target: "MovableToWishlist" },
      { source: "PrimeMembership", target: "PrimeAsinActionable" },
      { source: "PrimeExclusiveConfig", target: "PrimeAsinActionable" },
      { source: "ProductType", target: "PrimeAsinActionable" },
      { source: "PrimeProgramEligibility", target: "PrimeAsinActionable" },
      { source: "MembershipRetailPipelineConfig", target: "PrimeAsinActionable" },
      { source: "MembershipSharedConfig", target: "PrimeAsinActionable" },
      { source: "BuyboxWinner", target: "PrimeAsinActionable" },
      { source: "UnavailableOffer", target: "PrimeAsinActionable" },
      { source: "PantryPurchaseEligible", target: "PrimeAsinActionable" },
      { source: "ProductGroup", target: "PrimeAsinActionable" },
      { source: "Pantry", target: "PrimeAsinActionable" },
      { source: "Availability", target: "PrimeAsinActionable" },
      { source: "PrimeMembership", target: "Swipeable" },
      { source: "PrimeExclusiveConfig", target: "Swipeable" },
      { source: "ProductType", target: "Swipeable" },
      { source: "PrimeProgramEligibility", target: "Swipeable" },
      { source: "MembershipRetailPipelineConfig", target: "Swipeable" },
      { source: "MembershipSharedConfig", target: "Swipeable" },
      { source: "BuyboxWinner", target: "Swipeable" },
      { source: "UnavailableOffer", target: "Swipeable" },
      { source: "PantryPurchaseEligible", target: "Swipeable" },
      { source: "ProductGroup", target: "Swipeable" },
      { source: "Pantry", target: "Swipeable" },
      { source: "Availability", target: "Swipeable" },
      { source: "PrimeMembership", target: "MovableToSavedForLater" },
      { source: "PrimeExclusiveConfig", target: "MovableToSavedForLater" },
      { source: "ProductType", target: "MovableToSavedForLater" },
      { source: "PrimeProgramEligibility", target: "MovableToSavedForLater" },
      { source: "MembershipRetailPipelineConfig", target: "MovableToSavedForLater" },
      { source: "MembershipSharedConfig", target: "MovableToSavedForLater" },
      { source: "BuyboxWinner", target: "MovableToSavedForLater" },
      { source: "UnavailableOffer", target: "MovableToSavedForLater" },
      { source: "PantryPurchaseEligible", target: "MovableToSavedForLater" },
      { source: "ProductGroup", target: "MovableToSavedForLater" },
      { source: "Pantry", target: "MovableToSavedForLater" },
      { source: "Availability", target: "MovableToSavedForLater" },
      { source: "PrimeMembership", target: "Deletable" },
      { source: "PrimeExclusiveConfig", target: "Deletable" },
      { source: "ProductType", target: "Deletable" },
      { source: "PrimeProgramEligibility", target: "Deletable" },
      { source: "MembershipRetailPipelineConfig", target: "Deletable" },
      { source: "MembershipSharedConfig", target: "Deletable" },
      { source: "BuyboxWinner", target: "Deletable" },
      { source: "UnavailableOffer", target: "Deletable" },
      { source: "PantryPurchaseEligible", target: "Deletable" },
      { source: "ProductGroup", target: "Deletable" },
      { source: "Pantry", target: "Deletable" },
      { source: "Availability", target: "Deletable" },
      { source: "PrimeMembership", target: "PrimeJoinable" },
      { source: "PrimeExclusiveConfig", target: "PrimeJoinable" },
      { source: "ProductType", target: "PrimeJoinable" },
      { source: "PrimeProgramEligibility", target: "PrimeJoinable" },
      { source: "MembershipRetailPipelineConfig", target: "PrimeJoinable" },
      { source: "MembershipSharedConfig", target: "PrimeJoinable" },
      { source: "BuyboxWinner", target: "PrimeJoinable" },
      { source: "UnavailableOffer", target: "PrimeJoinable" },
      { source: "PantryPurchaseEligible", target: "PrimeJoinable" },
      { source: "ProductGroup", target: "PrimeJoinable" },
      { source: "Pantry", target: "PrimeJoinable" },
      { source: "Availability", target: "PrimeJoinable" },
      { source: "Pantry", target: "PantryBox" },
      { source: "PantryBoxBuilding", target: "PantryBox" },
      { source: "Fulfillment", target: "NoContactDeliveryTrustMessaging" },
      { source: "Fulfillment", target: "TrustMessaging" },
      { source: "SeeSimilarItemsBase", target: "SeeSimilarItems" },
      { source: "UnavailableOffer", target: "SeeSimilarItems" },
      { source: "ProductGroup", target: "SeeSimilarItems" },
      { source: "Availability", target: "SeeSimilarItems" },
      { source: "PantryBenefits", target: "PantrySubscriber" },
      { source: "ActiveCartLineItemCount", target: "BusinessQuoteBox" },
      { source: "PrimeMembership", target: "PantryDidYouForgetMessage" },
      { source: "PantryPurchaseEligible", target: "PantryDidYouForgetMessage" },
      { source: "PantryBenefits", target: "PantryDidYouForgetMessage" },
      { source: "FulfillmentManagerId", target: "PrimeMemberPromotion" },
      { source: "Price", target: "PrimeMemberPromotion" },
      { source: "ProductGroup", target: "PrimeMemberPromotion" },
      { source: "SubscribeAndSave", target: "PrimeMemberPromotion" },
      { source: "FulfillmentManagerId", target: "Coupon" },
      { source: "Price", target: "Coupon" },
      { source: "ProductGroup", target: "Coupon" },
      { source: "SubscribeAndSave", target: "Coupon" },
      { source: "LargeCartExperience", target: "PaginationButtons" },
      { source: "MadeForYouCustomizationId", target: "MadeForYouCustomizationDetails" },
      { source: "LightningDealPromotion", target: "LightningDeal" },
      { source: "PantryBoxBuilding", target: "ShippingWeight" },
      { source: "LocalMarketStoreName", target: "FreshDeliveryThreshold" },
      { source: "StoreChainOwnerId", target: "FreshDeliveryThreshold" },
      { source: "ItemSubtotals", target: "FreshDeliveryThreshold" },
      { source: "AddressIsPickup", target: "FreshDeliveryThreshold" },
      { source: "BrandId", target: "FreshDeliveryThreshold" },
      { source: "LocalMarketMembership", target: "FreshDeliveryThreshold" },
      { source: "RegionId", target: "FreshDeliveryThreshold" },
      { source: "SelectedOpenOrder", target: "FreshDeliveryThreshold" },
      { source: "LargeCartExperience", target: "ShowBusinessItemPrice" },
      { source: "PantryOrderThreshold", target: "PantryMinimumOrderViolation" },
      { source: "ContainsGlobalStoreItems", target: "ImportFeeDepositMessage" },
      { source: "ContainsRemoteFulfilledByAmazonItems", target: "ImportFeeDepositMessage" },
      { source: "InfoBlockDeliveryProgramForArbitration", target: "InfoBlockDeliveryProgram" },
      { source: "GiftCardCustomization", target: "InfoBlockDeliveryProgram" },
      { source: "Delivery", target: "InfoBlockDeliveryProgram" },
      { source: "PrimeMessaging", target: "InfoBlockDeliveryProgram" },
      { source: "InfoBlockDeliveryProgramForArbitration", target: "PrismaDelivery" },
      { source: "GiftCardCustomization", target: "PrismaDelivery" },
      { source: "Delivery", target: "PrismaDelivery" },
      { source: "PrimeMessaging", target: "PrismaDelivery" },
      { source: "InfoBlockDeliveryProgramForArbitration", target: "PrismaPrimeMessaging" },
      { source: "GiftCardCustomization", target: "PrismaPrimeMessaging" },
      { source: "Delivery", target: "PrismaPrimeMessaging" },
      { source: "PrimeMessaging", target: "PrismaPrimeMessaging" },
      { source: "PriceBeforeDiscount", target: "InfoBlockDeliveryProgram" },
      { source: "GiftCardCustomization", target: "InfoBlockDeliveryProgram" },
      { source: "Quantity", target: "InfoBlockDeliveryProgram" },
      { source: "ProductGroupUntyped", target: "InfoBlockDeliveryProgram" },
      { source: "PriceBeforeDiscount", target: "InfoBlockDeliveryProgramForArbitration" },
      { source: "GiftCardCustomization", target: "InfoBlockDeliveryProgramForArbitration" },
      { source: "Quantity", target: "InfoBlockDeliveryProgramForArbitration" },
      { source: "ProductGroupUntyped", target: "InfoBlockDeliveryProgramForArbitration" },
      { source: "PriceBeforeDiscount", target: "InfoBlockDeliveryProgramSubtitle" },
      { source: "GiftCardCustomization", target: "InfoBlockDeliveryProgramSubtitle" },
      { source: "Quantity", target: "InfoBlockDeliveryProgramSubtitle" },
      { source: "ProductGroupUntyped", target: "InfoBlockDeliveryProgramSubtitle" },
      { source: "BusinessCustomerMembership", target: "CompanyCompliancePolicy" },
      { source: "UnitOfMeasureQuantityPricing", target: "UnitOfMeasure" },
      { source: "SerializedSubscribeAndSaveData", target: "SubscribeAndSave" },
      { source: "SerializedSubscribeAndSaveData", target: "SubscribeAndSaveOfferData" },
      { source: "Pantry", target: "PantryShippingThreshold" },
      { source: "BrandId", target: "OfferListingDiscriminator" },
      { source: "BrandId", target: "StoreChainOwnerId" },
      { source: "BrandId", target: "LocalMarketStoreRanking" },
      { source: "BrandId", target: "LocalMarketBrandRefMarker" },
      { source: "BrandId", target: "LocalMarketNavStoreName" },
      { source: "PrimeMembership", target: "PantryDidYouForgetBuyMoreSaveMoreMessage" },
      { source: "PantrySubscriber", target: "PantryDidYouForgetBuyMoreSaveMoreMessage" },
      { source: "PantryPurchaseEligible", target: "PantryDidYouForgetBuyMoreSaveMoreMessage" },
      { source: "PrimeMembership", target: "TurboExperimentNonTriggeredWeblab" },
      { source: "ActiveCartLineItemCount", target: "TurboExperimentNonTriggeredWeblab" },
      { source: "PrimeExclusiveConfig", target: "ActiveCartErroneousImportantMessageList" },
      { source: "Price", target: "ActiveCartErroneousImportantMessageList" },
      { source: "AvailableSellerQuantity", target: "ActiveCartErroneousImportantMessageList" },
      { source: "PrimeExclusiveSelection", target: "ActiveCartErroneousImportantMessageList" },
      { source: "Quantity", target: "ActiveCartErroneousImportantMessageList" },
      { source: "PreviousPrice", target: "ActiveCartErroneousImportantMessageList" },
      { source: "DetailPageParams", target: "ActiveCartErroneousImportantMessageList" },
      { source: "ProductTitle", target: "ActiveCartErroneousImportantMessageList" },
      { source: "PantryOrderThreshold", target: "Interstitial" },
      { source: "AddonThreshold", target: "Interstitial" },
      { source: "PrimeMembership", target: "PantryPromotionUpsellMilestone" },
      { source: "Price", target: "PantryPromotionUpsellMilestone" },
      { source: "ProductGroup", target: "PantryPromotionUpsellMilestone" },
      { source: "Quantity", target: "PantryPromotionUpsellMilestone" },
      { source: "Pantry", target: "PantryPromotionUpsellMilestone" },
      { source: "OfferingSku", target: "PantryPromotionUpsellMilestone" },
      { source: "SellerBase", target: "PantryPromotionUpsellMilestone" },
      { source: "BrandId", target: "NavSearchScope" },
      { source: "GiftOption", target: "CartGiftOption" },
      { source: "MembershipSharedConfig", target: "CartGiftOption" },
      { source: "ProductGroup", target: "CartGiftOption" },
      { source: "FulfillmentManagerId", target: "PrimeMemberPromotion" },
      { source: "Price", target: "PrimeMemberPromotion" },
      { source: "ProductGroup", target: "PrimeMemberPromotion" },
      { source: "SubscribeAndSave", target: "PrimeMemberPromotion" },
      { source: "FulfillmentManagerId", target: "Coupon" },
      { source: "Price", target: "Coupon" },
      { source: "ProductGroup", target: "Coupon" },
      { source: "SubscribeAndSave", target: "Coupon" },
      { source: "RegionMismatch", target: "ActiveCartLineItemCount" },
      { source: "PrimeWardrobeIngress", target: "ActiveCartLineItemCount" },
      { source: "PantryFreeShippingEligible", target: "PantryBoxFreeShippingEligible" },
      { source: "Quantity", target: "PantryBoxFreeShippingEligible" },
      { source: "PantryBox", target: "PantryOrderThreshold" },
      { source: "GiftCardCustomization", target: "DisplayableAsin" },
      { source: "AddonThreshold", target: "UnpurchasableCart" },
      { source: "LocalMarketBrandRefMarker", target: "UnitOfMeasurePrice" },
      { source: "ProductImage", target: "UnitOfMeasurePrice" },
      { source: "LocalMarketBrandRefMarker", target: "UnitOfMeasureQuantitySelector" },
      { source: "ProductImage", target: "UnitOfMeasureQuantitySelector" },
      { source: "LocalMarketBrandRefMarker", target: "UnitOfMeasureEstimatedItemSubtotal" },
      { source: "ProductImage", target: "UnitOfMeasureEstimatedItemSubtotal" },
      { source: "ListId", target: "RegistryContributionTitle" },
      { source: "ListId", target: "RegistryWishLists" },
      { source: "ListId", target: "RegistryAlert" },
      { source: "ListId", target: "RegistryTitle" },
      { source: "ListId", target: "RegistryMessage" },
      { source: "ListId", target: "RegistryItemAsin" },
      { source: "BrandId", target: "RegionMismatch" },
      { source: "UltraFastGrocery", target: "CheckoutButton" },
      { source: "LocalMarketStoreName", target: "CheckoutButton" },
      { source: "PrimeMembership", target: "CheckoutButton" },
      { source: "ItemSubtotals", target: "CheckoutButton" },
      { source: "LocalMarketStoreShortName", target: "CheckoutButton" },
      { source: "FreshDeliveryThreshold", target: "CheckoutButton" },
      { source: "PickUpInStore", target: "CheckoutButton" },
      { source: "BrandId", target: "CheckoutButton" },
      { source: "PostOrderOverAuthMessage", target: "CheckoutButton" },
      { source: "LocalMarketMembership", target: "CheckoutButton" },
      { source: "SelectedOpenOrder", target: "CheckoutButton" },
      { source: "PrimeMembership", target: "LocalMarketPrimeUpsell" },
      { source: "LocalMarketMembership", target: "LocalMarketPrimeUpsell" },
      { source: "Price", target: "Points" },
      { source: "PointsBenefits", target: "Points" },
      { source: "PointsBase", target: "Points" },
      { source: "SerializedSubscribeAndSaveData", target: "SubscribeAndSaveDetails" },
      { source: "SubscribeAndSaveProductInformation", target: "SubscribeAndSaveDetails" },
      { source: "AppliedPromotions", target: "SubscribeAndSaveDetails" },
      { source: "SubscribeAndSave", target: "SubscribeAndSaveDetails" },
      { source: "ItemSubtotals", target: "LuxuryCartIngress" },
      { source: "UnbuyableDigitalCombo", target: "ContainsKindleUnlimited" },
      { source: "ProductGroup", target: "ContainsKindleUnlimited" },
      { source: "UnbuyableDigitalCombo", target: "CartSummaryVisualization" },
      { source: "ProductGroup", target: "CartSummaryVisualization" },
      { source: "UnbuyableDigitalCombo", target: "ContainsPrimeSubscription" },
      { source: "ProductGroup", target: "ContainsPrimeSubscription" },
      { source: "UnbuyableDigitalCombo", target: "CartSummary" },
      { source: "ProductGroup", target: "CartSummary" },
      { source: "IncludeLargeCartSavedCount", target: "LargeCartSavedCount" },
      { source: "LargeCartExperience", target: "LargeCartSavedCount" },
      { source: "IncludeLargeCartSavedCount", target: "LargeCartSubtotal" },
      { source: "LargeCartExperience", target: "LargeCartSubtotal" },
      { source: "SerializedSubscribeAndSaveData", target: "SubscribeAndSaveSmartWagonMessage" },
      { source: "FulfillmentManagerId", target: "PantryFreeShippingEligible" },
      { source: "Pantry", target: "PantryFreeShippingEligible" },
      { source: "OfferingSku", target: "PantryFreeShippingEligible" },
      { source: "SellerBase", target: "PantryFreeShippingEligible" },
      { source: "DiBSItemId", target: "LowConfidenceActiveCartLineItemCount" },
      { source: "ProductVariation", target: "AssemblyVariation" },
      { source: "AssemblyVariationId", target: "AssemblyVariation" },
      { source: "BuyboxWinnerPrice", target: "BuyboxWinner" },
      { source: "Price", target: "BuyboxWinner" },
      { source: "UnavailableOffer", target: "BuyboxWinner" },
      { source: "Binding", target: "BindingAndCondition" },
      { source: "Condition", target: "BindingAndCondition" },
      { source: "CompanyCompliancePolicy", target: "BlockedByYourCompanyCart" },
      { source: "QuantityInInventory", target: "ImportantMessageList" },
      { source: "Price", target: "ImportantMessageList" },
      { source: "Quantity", target: "ImportantMessageList" },
      { source: "PreviousPrice", target: "ImportantMessageList" },
      { source: "DetailPageParams", target: "ImportantMessageList" },
      { source: "ProductTitle", target: "ImportantMessageList" },
      { source: "ItemKeyValuePairs", target: "RecommendationContent" },
      { source: "LocationIntent", target: "RecommendationContent" },
      { source: "PrimeMembership", target: "RecommendationContent" },
      { source: "MostRecentlyAddedItem", target: "RecommendationContent" },
      { source: "Price", target: "RecommendationContent" },
      { source: "ItemSubtotals", target: "RecommendationContent" },
      { source: "PrimeProgramEligibility", target: "RecommendationContent" },
      { source: "SavedCartLineItemCount", target: "RecommendationContent" },
      { source: "ExportMode", target: "RecommendationContent" },
      { source: "AddedToCartTime", target: "RecommendationContent" },
      { source: "ProductGroupUntyped", target: "RecommendationContent" },
      { source: "PriceBeforeDiscount", target: "BenefitDeliveryProgramContent" },
      { source: "PrimeMembership", target: "BenefitDeliveryProgramContent" },
      { source: "AddonMessage", target: "BenefitDeliveryProgramContent" },
      { source: "UnitOfMeasureEstimatedItemSubtotal", target: "BenefitDeliveryProgramContent" },
      { source: "ExportMode", target: "BenefitDeliveryProgramContent" },
      { source: "Quantity", target: "BenefitDeliveryProgramContent" },
      { source: "ProductGroupUntyped", target: "BenefitDeliveryProgramContent" },
      { source: "PriceBeforeDiscount", target: "BuyBoxDeliveryProgramContent" },
      { source: "PrimeMembership", target: "BuyBoxDeliveryProgramContent" },
      { source: "AddonMessage", target: "BuyBoxDeliveryProgramContent" },
      { source: "UnitOfMeasureEstimatedItemSubtotal", target: "BuyBoxDeliveryProgramContent" },
      { source: "ExportMode", target: "BuyBoxDeliveryProgramContent" },
      { source: "Quantity", target: "BuyBoxDeliveryProgramContent" },
      { source: "ProductGroupUntyped", target: "BuyBoxDeliveryProgramContent" },
      { source: "BusinessCustomerMembership", target: "PunchoutCart" },
      { source: "FulfillmentManagerId", target: "AffordabilityWidget" },
      { source: "PrimeMembership", target: "AffordabilityWidget" },
      { source: "Price", target: "AffordabilityWidget" },
      { source: "BusinessCustomerMembership", target: "AffordabilityWidget" },
      { source: "Coupon", target: "AffordabilityWidget" },
      { source: "Quantity", target: "AffordabilityWidget" },
      { source: "OfferingSku", target: "AffordabilityWidget" },
      { source: "ProductTitle", target: "AffordabilityWidget" },
      { source: "RemoteFbaItem", target: "RemoteFbaMessage" },
      { source: "RemoteFbaItem", target: "RemoteFbaBadge" },
      { source: "UnavailableOffer", target: "OutOfStockItemCount" },
      { source: "Quantity", target: "OutOfStockItemCount" },
      { source: "Points", target: "PointsSubtotal" },
      { source: "Quantity", target: "PointsSubtotal" },
      { source: "Currency", target: "ItemSubtotals" },
      { source: "Price", target: "ItemSubtotals" },
      { source: "UnavailableOffer", target: "ItemSubtotals" },
      { source: "DepositPrice", target: "ItemSubtotals" },
      { source: "UnitOfMeasureEstimatedItemSubtotal", target: "ItemSubtotals" },
      { source: "LargeCartExperience", target: "ItemSubtotals" },
      { source: "ProductBundleDetail", target: "ItemSubtotals" },
      { source: "Quantity", target: "ItemSubtotals" },
      { source: "LargeCartSubtotal", target: "ItemSubtotals" },
      { source: "ProductType", target: "AlcoholConsent" },
      { source: "WarrantyProduct", target: "Availability" },
      { source: "ProductGroup", target: "Availability" },
      { source: "GiftCardCustomization", target: "Availability" },
      { source: "AvailabilityBase", target: "Availability" },
      { source: "ProductGroup", target: "DigitalPhysicalBundleMessage" },
      { source: "ActiveCartLineItemCount", target: "LargeCartExperience" },
      { source: "UnavailableOffer", target: "OtherOffers" },
      { source: "OtherOffersBase", target: "OtherOffers" },
      { source: "ProductGroup", target: "UnbuyableDigitalCombo" },
      { source: "StoreChainOwnerId", target: "LocalMarketMembership" },
      { source: "PrimeMembership", target: "LocalMarketMembership" },
      { source: "AddressIsPickup", target: "LocalMarketMembership" },
      { source: "BrandId", target: "LocalMarketMembership" },
      { source: "RegionId", target: "LocalMarketMembership" },
      { source: "DetailPageCustomId", target: "DetailPageParams" },
      { source: "AssemblyVariationId", target: "DetailPageParams" },
      { source: "Pantry", target: "DetailPageParams" },
      { source: "TheDropLimitedEditionOffer", target: "TheDropLimitedEditionOfferDetails" },
      { source: "UnavailableOffer", target: "SeeSimilarItems" },
      { source: "DiBSItemId", target: "UtteranceFeedback" },
      { source: "RestrictedByYourCompanyCart", target: "ActiveCartImportantMessageList" },
      { source: "BlockedByYourCompanyCart", target: "ActiveCartImportantMessageList" },
      { source: "ProductBundle", target: "ProductBundleDetail" },
      { source: "BrandId", target: "PickUpInStore" },
      { source: "UnitOfMeasure", target: "QuantityDisplayString" },
      { source: "Quantity", target: "QuantityDisplayString" },
      { source: "UltraFastGrocery", target: "ReservationPrimaryLink" },
      { source: "AddressLabel", target: "ReservationPrimaryLink" },
      { source: "AddressIsPickup", target: "ReservationPrimaryLink" },
      { source: "BrandId", target: "ReservationPrimaryLink" },
      { source: "RegionHasPickup", target: "ReservationPrimaryLink" },
      { source: "SelectedOpenOrder", target: "ReservationPrimaryLink" },
      { source: "UltraFastGrocery", target: "ReservationSecondaryLink" },
      { source: "AddressLabel", target: "ReservationSecondaryLink" },
      { source: "AddressIsPickup", target: "ReservationSecondaryLink" },
      { source: "BrandId", target: "ReservationSecondaryLink" },
      { source: "RegionHasPickup", target: "ReservationSecondaryLink" },
      { source: "SelectedOpenOrder", target: "ReservationSecondaryLink" },
      { source: "UltraFastGrocery", target: "ReservationSlotLabel" },
      { source: "AddressLabel", target: "ReservationSlotLabel" },
      { source: "AddressIsPickup", target: "ReservationSlotLabel" },
      { source: "BrandId", target: "ReservationSlotLabel" },
      { source: "RegionHasPickup", target: "ReservationSlotLabel" },
      { source: "SelectedOpenOrder", target: "ReservationSlotLabel" },
      { source: "PrimeMembership", target: "Delivery" },
      { source: "ProductGroup", target: "Delivery" },
      { source: "GiftCardCustomization", target: "Delivery" },
      { source: "AmazonGlobalStoreItem", target: "Delivery" },
      { source: "Fulfillment", target: "Delivery" },
      { source: "PrimeMembership", target: "PrimeMessaging" },
      { source: "ProductGroup", target: "PrimeMessaging" },
      { source: "GiftCardCustomization", target: "PrimeMessaging" },
      { source: "AmazonGlobalStoreItem", target: "PrimeMessaging" },
      { source: "Fulfillment", target: "PrimeMessaging" },
      { source: "Pantry", target: "PantryBenefits" },
      { source: "Price", target: "ImportantMessageList" },
      { source: "PreviousPrice", target: "ImportantMessageList" },
      { source: "DetailPageParams", target: "ImportantMessageList" },
      { source: "ProductTitle", target: "ImportantMessageList" },
      { source: "PickUpInStore", target: "DetailPageParams" },
      { source: "BrandId", target: "DetailPageParams" }
    ],
    nodes: [
      "ProductGroup",
      "LastModifiedDate",
      "RegistryContributionTitle",
      "LuxuryCartIngress",
      "SavedCartHasMoreItems",
      "SubscribeAndSaveOfferData",
      "LocalMarketMembership",
      "OtherOffers",
      "InfoBlockDeliveryProgramForArbitration",
      "SourceMarketplaceId",
      "Pantry",
      "LocationIntent",
      "InstantDiscountRecommendationSource",
      "InfoBlockDeliveryProgramSubtitle",
      "QuantityUpdateMessage",
      "Currency",
      "SerializedSubscribeAndSaveData",
      "ProductVariation",
      "CustomizationToken",
      "DisplayableAsin",
      "AddonThresholdSuppressedForAmazonDay",
      "PrimeMessaging",
      "RentalOfferDetails",
      "ItemSubtotals",
      "MovableToSavedForLater",
      "TheDropLimitedEditionOffer",
      "AmazonGlobalStoreItem",
      "UnitOfMeasureEstimatedItemSubtotal",
      "PointsBalance",
      "ReservationSecondaryLink",
      "GroupGiftingProductTitle",
      "ProductType",
      "OutOfStockItemCount",
      "QuantityInInventory",
      "ActiveCartLineItemCount",
      "Fulfillment",
      "CartGiftOption",
      "RegistryTitle",
      "AmbiguousBrandBase",
      "RelatedItemParent",
      "PrimeExclusiveSelection",
      "Deletable",
      "ShippingWeight",
      "DisableBusinessPTCButton",
      "ContainsRemoteFulfilledByAmazonItems",
      "RegistryAlert",
      "PointsBenefits",
      "BuyboxWinnerPrice",
      "ReservationSlotLabel",
      "PantryBoxBuilding",
      "ActiveCartErroneousImportantMessageList",
      "GiftOption",
      "Swipeable",
      "AmazonGlobalStoreSeller",
      "ContainsGlobalStoreItems",
      "CollapsedCart",
      "PantryDidYouForgetMessage",
      "RemoteFbaItem",
      "PostOrderOverAuthMessage",
      "ContainsKindleUnlimited",
      "AddedToCartTime",
      "ImportantMessageList",
      "SelectionState",
      "AlexaBadgingId",
      "ThresholdContribution",
      "ContinueShoppingMessage",
      "ItemListQualifier",
      "DetailPageParams",
      "BuyBoxDeliveryProgramContent",
      "UnavailableOffer",
      "MovableToCart",
      "SubscribeAndSaveOneTimePurchaseSavings",
      "SubscribeAndSaveProductInformation",
      "IncludeLargeCartSavedCount",
      "PantryFreeShippingEligible",
      "PointsSubtotal",
      "LightningDeal",
      "HasAddonItems",
      "EmiEligibilityMessage",
      "BuyboxWinner",
      "PantryPurchaseEligible",
      "RedirectAsin",
      "Customization",
      "LightningDealPromotion",
      "AddedTime",
      "PantryBoxFreeShippingEligible",
      "RegionHasPickup",
      "FreshDeliveryThreshold",
      "AddressIsPickup",
      "AddedWithInSixMonths",
      "PrimeProgramEligibility",
      "PrimeWardrobeIngress",
      "BusinessCustomerMembership",
      "CartPreSelectedShipOptionCheckbox",
      "PantrySubscriber",
      "NoContactDeliveryTrustMessaging",
      "PrimeExclusiveConfig",
      "PaginationButtons",
      "Interstitial",
      "PreviousPrice",
      "CompanyCompliancePolicy",
      "BusinessPriceBadge",
      "AddonReminder",
      "PantryOrderThreshold",
      "Binding",
      "ProductGroupUntyped",
      "LocalMarketStoreRanking",
      "UnitOfMeasure",
      "TurboExperimentNonTriggeredWeblab",
      "EasyShipMessagingIcon",
      "AppliedPromotions",
      "BusinessQuoteBox",
      "AlcoholConsent",
      "CustomerBenefitPriceSavings",
      "LocalMarketStoreShortName",
      "PantryBenefits",
      "SelectableSubset",
      "HBAEligibility",
      "SubscribeAndSaveSmartWagonMessage",
      "ClientSideViewModel",
      "SellerBase",
      "UnpurchasableCart",
      "CustomerBenefitSavingsBase",
      "ProductImage",
      "UtteranceFeedback",
      "UnitOfMeasureQuantityPricing",
      "OtherOffersBase",
      "GiftCardCustomizationId",
      "ExportMode",
      "RelatedItemChild",
      "RegionMismatch",
      "OfferListingDiscriminator",
      "BenefitDeliveryProgramContent",
      "TheDropLimitedEditionOfferDetails",
      "CustomerName",
      "LowConfidenceActiveCartLineItemCount",
      "ItemBrandBase",
      "DetailPageCustomId",
      "PrescriptionRequiredBadge",
      "Condition",
      "Coupon",
      "LoadMoreInsertOffset",
      "QuantityDisplayString",
      "Asin",
      "ProductBundle",
      "CartSummary",
      "PriceBeforeDiscount",
      "MinimumQuantity",
      "LocalMarketPrimeUpsell",
      "FreshItemAvailability",
      "LocalMarketTablet",
      "PantryBoxTotalSavings",
      "MembershipRetailPipelineConfig",
      "LocalMarketNavStoreName",
      "ParentAsin",
      "VariableGiftCard",
      "MovableToWishlist",
      "BusinessPriceType",
      "Seller",
      "Delivery",
      "PromotionBundle",
      "PurchaseProtectionTrustMessage",
      "ImportFeeDepositMessage",
      "GiftOptionBase",
      "CustomizedThumbnail",
      "IncentivizedCartUrl",
      "RelatedItemAssociationTypeMessage",
      "ReservationPrimaryLink",
      "MembershipSharedConfig",
      "AvailabilityBase",
      "UltraFastGrocery",
      "PrimeAsinActionable",
      "SavedCartLineItemCount",
      "LargeCartSavedCount",
      "PartialServerSetting",
      "CustomerOneClickStatus",
      "PrismaDelivery",
      "Subscription",
      "SnapEbtItemSubtotals",
      "BenefitPriceModalSignupUrl",
      "GiftCardCustomization",
      "ContainsPrimeSubscription",
      "NavSearchScope",
      "SelectedOpenOrder",
      "InstantDiscountTitleMessage",
      "LightningDealDelay",
      "UnitOfMeasurePrice",
      "PickUpInStore",
      "SeeSimilarItemsBase",
      "DepositPrice",
      "PointsBase",
      "PantryPromotionUpsellMilestone",
      "LargeCartExperience",
      "RentalItem",
      "PunchoutCart",
      "PrimeMembership",
      "WarrantyProduct",
      "RegistryWishLists",
      "ShowBusinessItemPrice",
      "PriceChange",
      "RecentlyAddedItem",
      "UnpurchasableByPantry",
      "TrustMessaging",
      "ProductBundleDetail",
      "PantryShippingThreshold",
      "AddedToCartSessionId",
      "DigitalPhysicalBundleMessage",
      "ProductTitle",
      "PrimeJoinable",
      "InfoBlockDeliveryProgram",
      "AddonMessage",
      "AssemblyVariationId",
      "FreeTradeZoneItem",
      "SeeSimilarItems",
      "PurchaseOrder",
      "FulfillmentManagerId",
      "OfferListingId",
      "RegistryMessage",
      "RecommendationContent",
      "RestrictedByYourCompanyCart",
      "DeviceRegistration",
      "BrandId",
      "DiBSItemId",
      "CartSummaryVisualization",
      "PrismaPrimeMessaging",
      "CheckoutButton",
      "InfinityCheckout",
      "Availability",
      "StoreChainOwnerId",
      "LineItemBuyNow",
      "SubscribeAndSaveDetails",
      "AvailableSellerQuantity",
      "CartBrandBase",
      "SavedCartErroneousImportantMessageList",
      "SubscribeAndSave",
      "UnitOfMeasureQuantitySelector",
      "Price",
      "GroupGiftingProductImage",
      "LargeCartSubtotal",
      "Destination",
      "AddonThreshold",
      "RegistryItemAsin",
      "SnapEbtEligibility",
      "LocalMarketStoreName",
      "PantryMinimumOrderViolation",
      "FinancingMessage",
      "AddedWithInAWeek",
      "MadeForYouCustomizationDetails",
      "Points",
      "ListId",
      "RetailCartIngress",
      "BlockedByYourCompanyCart",
      "RemoteFbaMessage",
      "BuyNow",
      "PantryDidYouForgetBuyMoreSaveMoreMessage",
      "RemoteFbaBadge",
      "PantryBox",
      "BindingAndCondition",
      "Installments",
      "Addon",
      "MadeForYouCustomizationId",
      "UnbuyableDigitalCombo",
      "AddonMessageBase",
      "LocalMarketBadge",
      "LocalMarketBrandRefMarker",
      "Quantity",
      "MostRecentlyAddedItem",
      "OfferDataForBlacklisting",
      "AssemblyVariation",
      "ItemKeyValuePairs",
      "OfferingSku",
      "ActiveCartImportantMessageList",
      "AddressLabel",
      "PrimeMemberPromotion",
      "RegionId",
      "InstallmentsDetail",
      "HasSingleSelectedActiveItem",
      "AffordabilityWidget"
    ]
  };
}

export { fetchData };
